### ISSUE TITLE
XQuery Pow Wow on Tuesday 3/3/2020

### ISSUE THREAD

**Issue by frabbitry** [robftg/Rocket-Launches#15]
@biancamaginley @robftg 

Do you guys want to meet up and learn some XQuery tomorrow? I can be in the Center from 11:30-6pm. What time would work for you guys? 

This is possibly an opportunity to make up lost homework assignments, too. If I feel like you guys have done the equivalent of a homework assignment (XQuery 1, XPath 3, etc.), then I'll let @ebeshero know, and she can count that as you having passed the homework. 

We can even kick out @BMT45 if he's getting in the way :wink:

**Comment by biancamaginley** [comment]
That sounds great! The only problem is that I have to take a CSM on a tour of pitt greensburg at 2 and I have a quiz at 12:15 so I can meet between those times.

**Comment by frabbitry** [comment]
@biancamaginley Ok, so would you like to meet at 12:30? When do you think that your quiz will be done?

**Comment by frabbitry** [comment]
@biancamaginley @robftg 
Dr. B is having a meeting in the Center now, but I'm available on the chairs by the bookcases downstairs in FOB if you want to drop by. I'l be relocating to the Center in a bit, and I'll probably leave at 2pm. Of course, I also have office hours from 4:30-6pm if you want to drop in then.
