### ISSUE TITLE
part 1 

### ISSUE THREAD

**Issue by biancamaginley** [robftg/Rocket-Launches#7]
Hey i finished up parts 2, 3, and 4 other than the new element, type, and org. How are into the 1st part are you? I wanna keep going and get this part completely done.

**Comment by biancamaginley** [comment]
@robftg

**Comment by robftg** [comment]
I'll have the entire volume done Thursday evening/Friday morning.

**Comment by biancamaginley** [comment]
Im saying that i can finish volume one now if you tell me which ones you've done. I'm not sure if you're up to date on your commits

**Comment by robftg** [comment]
I have up to 130 done. I'll push them ASAP
